name: SwiftFeatureFlagKitDemo
options:
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
packages:
  SwiftFeatureFlagKit:
    path: ../../SDK/SwiftFeatureFlagKit
targets:
  FeatureFlagDemoApp:
    type: application
    platform: iOS
    sources:
      - App/Sources
      - App/Assets.xcassets
    dependencies:
      - package: SwiftFeatureFlagKit
        product: SwiftFeatureFlagKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cc.FeatureFlagDemoApp
        PRODUCT_NAME: FeatureFlagDemoApp
        SWIFT_VERSION: 6.0
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: 15.0
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
schemes:
  FeatureFlagDemoApp:
    build:
      targets:
        FeatureFlagDemoApp: all
    run:
      config: Debug
    archive:
      config: Release
